# Generated by Django 2.2.4 on 2019-11-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlinker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('website_link', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
