# Generated by Django 2.2.4 on 2019-11-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinker',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
