# Generated by Django 2.2.4 on 2019-12-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20191111_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinker',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='urlinker',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='urlinker',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urlinker',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='urlinker',
            name='website_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
