# Generated by Django 2.2.4 on 2019-12-17 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20191217_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlinker',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='urlinker',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlinker',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlinker',
            name='website_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
