# Generated by Django 2.2.4 on 2019-12-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20191217_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinker',
            name='images',
            field=models.ImageField(null=True, upload_to='ab/media/images/'),
        ),
    ]
