# Generated by Django 2.2.4 on 2019-12-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20191217_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinker',
            name='images',
            field=models.ImageField(blank=True, default='images/def.jpg', null=True, upload_to='images/'),
        ),
    ]
